"""empty message

Revision ID: 495e4f1930d4
Revises: 958ac472dc08
Create Date: 2024-06-18 01:07:15.209130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495e4f1930d4'
down_revision = '958ac472dc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    #op.execute('ALTER TABLE summary ALTER COLUMN id TYPE UUID USING id::uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
